<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="projectMdd" nsURI="http://www.example.org/projectMdd" nsPrefix="projectMdd">
  <eClassifiers xsi:type="ecore:EClass" name="Backend">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relation" upperBound="-1"
        eType="#//Relation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="database" lowerBound="1"
        eType="#//Database" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectDescription" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//InwardEntity #//OutwardEntity #//Persistable #//Displayable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relation" eSuperTypes="#//Persistable #//Displayable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" lowerBound="1" eType="#//Entity"
        eOpposite="#//OutwardEntity/outwardRelations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="1" eType="#//Entity"
        eOpposite="#//InwardEntity/inwardRelations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//RelationType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutwardEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outwardRelations" upperBound="-1"
        eType="#//Relation" eOpposite="#//Relation/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InwardEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inwardRelations" upperBound="-1"
        eType="#//Relation" eOpposite="#//Relation/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RelationType">
    <eLiterals name="oneToOne"/>
    <eLiterals name="oneToMany" value="1"/>
    <eLiterals name="ManyToMany" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Persistable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" abstract="true" eSuperTypes="#//Persistable #//Displayable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataType">
    <eLiterals name="String"/>
    <eLiterals name="Integer" value="1"/>
    <eLiterals name="Double" value="2"/>
    <eLiterals name="Char" value="3"/>
    <eLiterals name="Boolean" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Displayable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="display" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Database">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumAttribute" eSuperTypes="#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeAttribute" eSuperTypes="#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//DataType"/>
  </eClassifiers>
</ecore:EPackage>
